---
language: bash
services: docker

env:
  - VERSION=2.8 LATEST=true
  - VERSION=2.5

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - export IMAGE="mini/ansible:${VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker pull "$IMAGE" || true
      travis_retry docker build --cache-from "$IMAGE" -t "$IMAGE" $VERSION/
      IMAGE=$IMAGE VERSION=$VERSION bats tests/
    )

after_script:
  - docker images

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
